version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB=genesis
      - USER_COLLECTION=users
      - CATEGORY_COLLECTION=categories
      - PRODUCT_COLLECTION=products
      - VARIANT_COLLECTION=variants
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
